import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Neden from "@/components/Neden";
import Button from "@/components/Button";
import { getRandomIndex } from "@/helper";
import { nedenler } from "../../nedenler";
import React from "react";
import YouTube from "react-youtube";

export default function Home() {
  const [index, setIndex] = React.useState(0);
  console.log(index);
  return (
    <>
      <Head>
        <title>Seçim 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {nedenler && (
          <div className="flex flex-col max-lg:gap-16 lg:flex-row  justify-between w-full items-center">
            <div className="flex flex-col lg:w-5/12 gap-8">
              <Neden
                info={nedenler[index].info}
                paragraph={nedenler[index].paragraph}
                conclusion={nedenler[index].conclusion}
              />
              <div className="button-group relative flex gap-6">
                <Button
                  text={"Reisle Devam"}
                  onClick={() => setIndex(getRandomIndex())}
                />
                <Button
                  onClick={() => window.open("http://www.chp.org.tr")}
                  text={"Artık Yeter!"}
                  yeter
                />{" "}
                <h2 className="text-5xl whitespace-nowrap absolute opacity-10  top-16 font-extralight ">
                  KARAR SENİN
                </h2>
              </div>
            </div>
            <div className="flex flex-col items-center justify-center gap-8">
              <div className="bg-slate-800 p-2 rounded-md">
                <YouTube
                  videoId={nedenler[index].embed}
                  opts={{ height: "290", width: "440" }}
                ></YouTube>
              </div>
            </div>
          </div>
        )}{" "}
      </main>
    </>
  );
}
